package hibernate;


// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Comunidad generated by hbm2java
 */
public class Comunidad implements java.io.Serializable {

	private int idComunidad;
	private String calle;
	private Integer maxRecibosPendientes;
	private String estado;
	private Set facturas = new HashSet(0);
	private Set notaInformativas = new HashSet(0);
	private Set inmuebles = new HashSet(0);

	public Comunidad() {
	}

	public Comunidad(int idComunidad) {
		this.idComunidad = idComunidad;
	}

	public Comunidad(int idComunidad, String calle,
			Integer maxRecibosPendientes, String estado, Set facturas,
			Set notaInformativas, Set inmuebles) {
		this.idComunidad = idComunidad;
		this.calle = calle;
		this.maxRecibosPendientes = maxRecibosPendientes;
		this.estado = estado;
		this.facturas = facturas;
		this.notaInformativas = notaInformativas;
		this.inmuebles = inmuebles;
	}

	public int getIdComunidad() {
		return this.idComunidad;
	}

	public void setIdComunidad(int idComunidad) {
		this.idComunidad = idComunidad;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public Integer getMaxRecibosPendientes() {
		return this.maxRecibosPendientes;
	}

	public void setMaxRecibosPendientes(Integer maxRecibosPendientes) {
		this.maxRecibosPendientes = maxRecibosPendientes;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getNotaInformativas() {
		return this.notaInformativas;
	}

	public void setNotaInformativas(Set notaInformativas) {
		this.notaInformativas = notaInformativas;
	}

	public Set getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set inmuebles) {
		this.inmuebles = inmuebles;
	}

	
	
}
