// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA
package hibernate;


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private int numFactura;
	private NotaInformativa notaInformativa;
	private Comunidad comunidad;
	private String fechaFactura;
	private Set <LineaFactura> lineaFacturas = new HashSet(0);

	public Factura() {
	}

	public Factura(int numFactura, Comunidad comunidad) {
		this.numFactura = numFactura;
		this.comunidad = comunidad;
	}

	public Factura(int numFactura, NotaInformativa notaInformativa,
			Comunidad comunidad, String fechaFactura, Set lineaFacturas) {
		this.numFactura = numFactura;
		this.notaInformativa = notaInformativa;
		this.comunidad = comunidad;
		this.fechaFactura = fechaFactura;
		this.lineaFacturas = lineaFacturas;
	}

	public int getNumFactura() {
		return this.numFactura;
	}

	public void setNumFactura(int numFactura) {
		this.numFactura = numFactura;
	}

	public NotaInformativa getNotaInformativa() {
		return this.notaInformativa;
	}

	public void setNotaInformativa(NotaInformativa notaInformativa) {
		this.notaInformativa = notaInformativa;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura(String fechaFactura) {
		this.fechaFactura = fechaFactura;
	}

	public Set getLineaFacturas() {
		return this.lineaFacturas;
	}

	public void setLineaFacturas(Set lineaFacturas) {
		this.lineaFacturas = lineaFacturas;
	}
	
}
