// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA
package hibernate;


/**
 * LineaFactura generated by hbm2java
 */
public class LineaFactura implements java.io.Serializable {

	private int idLinea;
	private Factura factura;
	private Concepto concepto;
	private Double importeLinea;
	private String observacion;

	public LineaFactura() {
	}

	public LineaFactura(int idLinea, Factura factura, Concepto concepto) {
		this.idLinea = idLinea;
		this.factura = factura;
		this.concepto = concepto;
	}

	public LineaFactura(int idLinea, Factura factura, Concepto concepto,
			Double importeLinea, String observacion) {
		this.idLinea = idLinea;
		this.factura = factura;
		this.concepto = concepto;
		this.importeLinea = importeLinea;
		this.observacion = observacion;
	}

	public int getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(int idLinea) {
		this.idLinea = idLinea;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Concepto getConcepto() {
		return this.concepto;
	}

	public void setConcepto(Concepto concepto) {
		this.concepto = concepto;
	}

	public Double getImporteLinea() {
		return this.importeLinea;
	}

	public void setImporteLinea(Double importeLinea) {
		this.importeLinea = importeLinea;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
