// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA
package hibernate;


import java.util.HashSet;
import java.util.Set;

/**
 * NotaInformativa generated by hbm2java
 */
public class NotaInformativa implements java.io.Serializable {

	private int idNota;
	private Comunidad comunidad;
	private String fechaCalculo;
	private Double importeNota;
	private Set facturas = new HashSet(0);
	private Set reciboInmuebles = new HashSet(0);

	public NotaInformativa() {
	}

	public NotaInformativa(int idNota, Comunidad comunidad) {
		this.idNota = idNota;
		this.comunidad = comunidad;
	}

	public NotaInformativa(int idNota, Comunidad comunidad,
			String fechaCalculo, Double importeNota, Set facturas,
			Set reciboInmuebles) {
		this.idNota = idNota;
		this.comunidad = comunidad;
		this.fechaCalculo = fechaCalculo;
		this.importeNota = importeNota;
		this.facturas = facturas;
		this.reciboInmuebles = reciboInmuebles;
	}

	public int getIdNota() {
		return this.idNota;
	}

	public void setIdNota(int idNota) {
		this.idNota = idNota;
	}

	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	public String getFechaCalculo() {
		return this.fechaCalculo;
	}

	public void setFechaCalculo(String fechaCalculo) {
		this.fechaCalculo = fechaCalculo;
	}

	public Double getImporteNota() {
		return this.importeNota;
	}

	public void setImporteNota(Double importeNota) {
		this.importeNota = importeNota;
	}

	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

	public Set getReciboInmuebles() {
		return this.reciboInmuebles;
	}

	public void setReciboInmuebles(Set reciboInmuebles) {
		this.reciboInmuebles = reciboInmuebles;
	}

}
