// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA
package hibernate;


import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
public class Propietario implements java.io.Serializable {

	private int nif;
	private String nombre;
	private String direccion;
	private String poblacion;
	private String telefono;
	private String observaciones;
	private String fechaAlta;
	private String entidad;
	private String numeroCuenta;
	private Set inmuebles = new HashSet(0);

	public Propietario() {
	}

	public Propietario(int nif) {
		this.nif = nif;
	}

	public Propietario(int nif, String nombre, String direccion,
			String poblacion, String telefono, String observaciones,
			String fechaAlta, String entidad, String numeroCuenta, Set inmuebles) {
		this.nif = nif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.observaciones = observaciones;
		this.fechaAlta = fechaAlta;
		this.entidad = entidad;
		this.numeroCuenta = numeroCuenta;
		this.inmuebles = inmuebles;
	}

	public int getNif() {
		return this.nif;
	}

	public void setNif(int nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(String fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

	public String getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public Set getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set inmuebles) {
		this.inmuebles = inmuebles;
	}

}
