// default package
// Generated 29-abr-2013 19:22:02 by Hibernate Tools 3.2.4.GA
package hibernate;


/**
 * ReciboInmueble generated by hbm2java
 */
public class ReciboInmueble implements java.io.Serializable {

	private int idRecibo;
	private NotaInformativa notaInformativa;
	private Inmueble inmueble;
	private String fechaPago;
	private Double importe;

	public ReciboInmueble() {
	}

	public ReciboInmueble(int idRecibo) {
		this.idRecibo = idRecibo;
	}

	public ReciboInmueble(int idRecibo, NotaInformativa notaInformativa,
			Inmueble inmueble, String fechaPago, Double importe) {
		this.idRecibo = idRecibo;
		this.notaInformativa = notaInformativa;
		this.inmueble = inmueble;
		this.fechaPago = fechaPago;
		this.importe = importe;
	}

	public int getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(int idRecibo) {
		this.idRecibo = idRecibo;
	}

	public NotaInformativa getNotaInformativa() {
		return this.notaInformativa;
	}

	public void setNotaInformativa(NotaInformativa notaInformativa) {
		this.notaInformativa = notaInformativa;
	}

	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	public String getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(String fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Double getImporte() {
		return this.importe;
	}

	public void setImporte(Double importe) {
		this.importe = importe;
	}

}
